/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TtdCutiSwastaRouteImport } from './routes/ttd-cuti-swasta'
import { Route as TtdCutiRouteImport } from './routes/ttd-cuti'
import { Route as RiwayatCutiRouteImport } from './routes/riwayat-cuti'
import { Route as ProsedurRouteImport } from './routes/prosedur'
import { Route as KetentuanRouteImport } from './routes/ketentuan'
import { Route as EPresensiRouteImport } from './routes/e-presensi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SyaratBerkasIndexRouteImport } from './routes/syarat-berkas/index'
import { Route as SwastaIndexRouteImport } from './routes/swasta/index'
import { Route as PybIndexRouteImport } from './routes/pyb/index'
import { Route as PppkIndexRouteImport } from './routes/pppk/index'
import { Route as PnsNegeriIndexRouteImport } from './routes/pns-negeri/index'
import { Route as PengajuanCutiIndexRouteImport } from './routes/pengajuan-cuti/index'
import { Route as DasarHukumIndexRouteImport } from './routes/dasar-hukum/index'
import { Route as PppkJenisRouteImport } from './routes/pppk/jenis'
import { Route as PnsNegeriJenisCutiRouteImport } from './routes/pns-negeri/jenis-cuti'
import { Route as SwastaCutiBesarIndexRouteImport } from './routes/swasta/cutiBesar/index'
import { Route as SwastaCutiTahunanIndexRouteImport } from './routes/swasta/cuti-tahunan/index'
import { Route as SwastaCutiSakitIndexRouteImport } from './routes/swasta/cuti-sakit/index'
import { Route as SwastaCutiMelahirkanIndexRouteImport } from './routes/swasta/cuti-melahirkan/index'
import { Route as SwastaCutiAlasanPentingIndexRouteImport } from './routes/swasta/cuti-alasan-penting/index'
import { Route as SwastaCltnIndexRouteImport } from './routes/swasta/cltn/index'
import { Route as PppkCutiTahunanIndexRouteImport } from './routes/pppk/cuti-tahunan/index'
import { Route as PppkCutiSakitIndexRouteImport } from './routes/pppk/cuti-sakit/index'
import { Route as PppkCutiMelahirkanIndexRouteImport } from './routes/pppk/cuti-melahirkan/index'
import { Route as PnsNegeriTahunanNegeriIndexRouteImport } from './routes/pns-negeri/tahunan-negeri/index'
import { Route as PnsNegeriSakitNegeriSakitNegeriRouteImport } from './routes/pns-negeri/sakit-negeri/sakit-negeri'
import { Route as PnsNegeriNegeriBesarBesarNegeriRouteImport } from './routes/pns-negeri/negeri-besar/besar-negeri'
import { Route as PnsNegeriMelahirkanNegeriMelahirkanNegriRouteImport } from './routes/pns-negeri/melahirkan-negeri/melahirkan-negri'
import { Route as PnsNegeriCltnNegeriCltnNegriRouteImport } from './routes/pns-negeri/cltn-negeri/cltn-negri'
import { Route as PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRouteImport } from './routes/pns-negeri/alasanPenting-negeri/alasanPenting-negeri'

const TtdCutiSwastaRoute = TtdCutiSwastaRouteImport.update({
  id: '/ttd-cuti-swasta',
  path: '/ttd-cuti-swasta',
  getParentRoute: () => rootRouteImport,
} as any)
const TtdCutiRoute = TtdCutiRouteImport.update({
  id: '/ttd-cuti',
  path: '/ttd-cuti',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatCutiRoute = RiwayatCutiRouteImport.update({
  id: '/riwayat-cuti',
  path: '/riwayat-cuti',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsedurRoute = ProsedurRouteImport.update({
  id: '/prosedur',
  path: '/prosedur',
  getParentRoute: () => rootRouteImport,
} as any)
const KetentuanRoute = KetentuanRouteImport.update({
  id: '/ketentuan',
  path: '/ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const EPresensiRoute = EPresensiRouteImport.update({
  id: '/e-presensi',
  path: '/e-presensi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratBerkasIndexRoute = SyaratBerkasIndexRouteImport.update({
  id: '/syarat-berkas/',
  path: '/syarat-berkas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwastaIndexRoute = SwastaIndexRouteImport.update({
  id: '/swasta/',
  path: '/swasta/',
  getParentRoute: () => rootRouteImport,
} as any)
const PybIndexRoute = PybIndexRouteImport.update({
  id: '/pyb/',
  path: '/pyb/',
  getParentRoute: () => rootRouteImport,
} as any)
const PppkIndexRoute = PppkIndexRouteImport.update({
  id: '/pppk/',
  path: '/pppk/',
  getParentRoute: () => rootRouteImport,
} as any)
const PnsNegeriIndexRoute = PnsNegeriIndexRouteImport.update({
  id: '/pns-negeri/',
  path: '/pns-negeri/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengajuanCutiIndexRoute = PengajuanCutiIndexRouteImport.update({
  id: '/pengajuan-cuti/',
  path: '/pengajuan-cuti/',
  getParentRoute: () => rootRouteImport,
} as any)
const DasarHukumIndexRoute = DasarHukumIndexRouteImport.update({
  id: '/dasar-hukum/',
  path: '/dasar-hukum/',
  getParentRoute: () => rootRouteImport,
} as any)
const PppkJenisRoute = PppkJenisRouteImport.update({
  id: '/pppk/jenis',
  path: '/pppk/jenis',
  getParentRoute: () => rootRouteImport,
} as any)
const PnsNegeriJenisCutiRoute = PnsNegeriJenisCutiRouteImport.update({
  id: '/pns-negeri/jenis-cuti',
  path: '/pns-negeri/jenis-cuti',
  getParentRoute: () => rootRouteImport,
} as any)
const SwastaCutiBesarIndexRoute = SwastaCutiBesarIndexRouteImport.update({
  id: '/swasta/cutiBesar/',
  path: '/swasta/cutiBesar/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwastaCutiTahunanIndexRoute = SwastaCutiTahunanIndexRouteImport.update({
  id: '/swasta/cuti-tahunan/',
  path: '/swasta/cuti-tahunan/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwastaCutiSakitIndexRoute = SwastaCutiSakitIndexRouteImport.update({
  id: '/swasta/cuti-sakit/',
  path: '/swasta/cuti-sakit/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwastaCutiMelahirkanIndexRoute =
  SwastaCutiMelahirkanIndexRouteImport.update({
    id: '/swasta/cuti-melahirkan/',
    path: '/swasta/cuti-melahirkan/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SwastaCutiAlasanPentingIndexRoute =
  SwastaCutiAlasanPentingIndexRouteImport.update({
    id: '/swasta/cuti-alasan-penting/',
    path: '/swasta/cuti-alasan-penting/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SwastaCltnIndexRoute = SwastaCltnIndexRouteImport.update({
  id: '/swasta/cltn/',
  path: '/swasta/cltn/',
  getParentRoute: () => rootRouteImport,
} as any)
const PppkCutiTahunanIndexRoute = PppkCutiTahunanIndexRouteImport.update({
  id: '/pppk/cuti-tahunan/',
  path: '/pppk/cuti-tahunan/',
  getParentRoute: () => rootRouteImport,
} as any)
const PppkCutiSakitIndexRoute = PppkCutiSakitIndexRouteImport.update({
  id: '/pppk/cuti-sakit/',
  path: '/pppk/cuti-sakit/',
  getParentRoute: () => rootRouteImport,
} as any)
const PppkCutiMelahirkanIndexRoute = PppkCutiMelahirkanIndexRouteImport.update({
  id: '/pppk/cuti-melahirkan/',
  path: '/pppk/cuti-melahirkan/',
  getParentRoute: () => rootRouteImport,
} as any)
const PnsNegeriTahunanNegeriIndexRoute =
  PnsNegeriTahunanNegeriIndexRouteImport.update({
    id: '/pns-negeri/tahunan-negeri/',
    path: '/pns-negeri/tahunan-negeri/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PnsNegeriSakitNegeriSakitNegeriRoute =
  PnsNegeriSakitNegeriSakitNegeriRouteImport.update({
    id: '/pns-negeri/sakit-negeri/sakit-negeri',
    path: '/pns-negeri/sakit-negeri/sakit-negeri',
    getParentRoute: () => rootRouteImport,
  } as any)
const PnsNegeriNegeriBesarBesarNegeriRoute =
  PnsNegeriNegeriBesarBesarNegeriRouteImport.update({
    id: '/pns-negeri/negeri-besar/besar-negeri',
    path: '/pns-negeri/negeri-besar/besar-negeri',
    getParentRoute: () => rootRouteImport,
  } as any)
const PnsNegeriMelahirkanNegeriMelahirkanNegriRoute =
  PnsNegeriMelahirkanNegeriMelahirkanNegriRouteImport.update({
    id: '/pns-negeri/melahirkan-negeri/melahirkan-negri',
    path: '/pns-negeri/melahirkan-negeri/melahirkan-negri',
    getParentRoute: () => rootRouteImport,
  } as any)
const PnsNegeriCltnNegeriCltnNegriRoute =
  PnsNegeriCltnNegeriCltnNegriRouteImport.update({
    id: '/pns-negeri/cltn-negeri/cltn-negri',
    path: '/pns-negeri/cltn-negeri/cltn-negri',
    getParentRoute: () => rootRouteImport,
  } as any)
const PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRoute =
  PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRouteImport.update({
    id: '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri',
    path: '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e-presensi': typeof EPresensiRoute
  '/ketentuan': typeof KetentuanRoute
  '/prosedur': typeof ProsedurRoute
  '/riwayat-cuti': typeof RiwayatCutiRoute
  '/ttd-cuti': typeof TtdCutiRoute
  '/ttd-cuti-swasta': typeof TtdCutiSwastaRoute
  '/pns-negeri/jenis-cuti': typeof PnsNegeriJenisCutiRoute
  '/pppk/jenis': typeof PppkJenisRoute
  '/dasar-hukum': typeof DasarHukumIndexRoute
  '/pengajuan-cuti': typeof PengajuanCutiIndexRoute
  '/pns-negeri': typeof PnsNegeriIndexRoute
  '/pppk': typeof PppkIndexRoute
  '/pyb': typeof PybIndexRoute
  '/swasta': typeof SwastaIndexRoute
  '/syarat-berkas': typeof SyaratBerkasIndexRoute
  '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri': typeof PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRoute
  '/pns-negeri/cltn-negeri/cltn-negri': typeof PnsNegeriCltnNegeriCltnNegriRoute
  '/pns-negeri/melahirkan-negeri/melahirkan-negri': typeof PnsNegeriMelahirkanNegeriMelahirkanNegriRoute
  '/pns-negeri/negeri-besar/besar-negeri': typeof PnsNegeriNegeriBesarBesarNegeriRoute
  '/pns-negeri/sakit-negeri/sakit-negeri': typeof PnsNegeriSakitNegeriSakitNegeriRoute
  '/pns-negeri/tahunan-negeri': typeof PnsNegeriTahunanNegeriIndexRoute
  '/pppk/cuti-melahirkan': typeof PppkCutiMelahirkanIndexRoute
  '/pppk/cuti-sakit': typeof PppkCutiSakitIndexRoute
  '/pppk/cuti-tahunan': typeof PppkCutiTahunanIndexRoute
  '/swasta/cltn': typeof SwastaCltnIndexRoute
  '/swasta/cuti-alasan-penting': typeof SwastaCutiAlasanPentingIndexRoute
  '/swasta/cuti-melahirkan': typeof SwastaCutiMelahirkanIndexRoute
  '/swasta/cuti-sakit': typeof SwastaCutiSakitIndexRoute
  '/swasta/cuti-tahunan': typeof SwastaCutiTahunanIndexRoute
  '/swasta/cutiBesar': typeof SwastaCutiBesarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e-presensi': typeof EPresensiRoute
  '/ketentuan': typeof KetentuanRoute
  '/prosedur': typeof ProsedurRoute
  '/riwayat-cuti': typeof RiwayatCutiRoute
  '/ttd-cuti': typeof TtdCutiRoute
  '/ttd-cuti-swasta': typeof TtdCutiSwastaRoute
  '/pns-negeri/jenis-cuti': typeof PnsNegeriJenisCutiRoute
  '/pppk/jenis': typeof PppkJenisRoute
  '/dasar-hukum': typeof DasarHukumIndexRoute
  '/pengajuan-cuti': typeof PengajuanCutiIndexRoute
  '/pns-negeri': typeof PnsNegeriIndexRoute
  '/pppk': typeof PppkIndexRoute
  '/pyb': typeof PybIndexRoute
  '/swasta': typeof SwastaIndexRoute
  '/syarat-berkas': typeof SyaratBerkasIndexRoute
  '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri': typeof PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRoute
  '/pns-negeri/cltn-negeri/cltn-negri': typeof PnsNegeriCltnNegeriCltnNegriRoute
  '/pns-negeri/melahirkan-negeri/melahirkan-negri': typeof PnsNegeriMelahirkanNegeriMelahirkanNegriRoute
  '/pns-negeri/negeri-besar/besar-negeri': typeof PnsNegeriNegeriBesarBesarNegeriRoute
  '/pns-negeri/sakit-negeri/sakit-negeri': typeof PnsNegeriSakitNegeriSakitNegeriRoute
  '/pns-negeri/tahunan-negeri': typeof PnsNegeriTahunanNegeriIndexRoute
  '/pppk/cuti-melahirkan': typeof PppkCutiMelahirkanIndexRoute
  '/pppk/cuti-sakit': typeof PppkCutiSakitIndexRoute
  '/pppk/cuti-tahunan': typeof PppkCutiTahunanIndexRoute
  '/swasta/cltn': typeof SwastaCltnIndexRoute
  '/swasta/cuti-alasan-penting': typeof SwastaCutiAlasanPentingIndexRoute
  '/swasta/cuti-melahirkan': typeof SwastaCutiMelahirkanIndexRoute
  '/swasta/cuti-sakit': typeof SwastaCutiSakitIndexRoute
  '/swasta/cuti-tahunan': typeof SwastaCutiTahunanIndexRoute
  '/swasta/cutiBesar': typeof SwastaCutiBesarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e-presensi': typeof EPresensiRoute
  '/ketentuan': typeof KetentuanRoute
  '/prosedur': typeof ProsedurRoute
  '/riwayat-cuti': typeof RiwayatCutiRoute
  '/ttd-cuti': typeof TtdCutiRoute
  '/ttd-cuti-swasta': typeof TtdCutiSwastaRoute
  '/pns-negeri/jenis-cuti': typeof PnsNegeriJenisCutiRoute
  '/pppk/jenis': typeof PppkJenisRoute
  '/dasar-hukum/': typeof DasarHukumIndexRoute
  '/pengajuan-cuti/': typeof PengajuanCutiIndexRoute
  '/pns-negeri/': typeof PnsNegeriIndexRoute
  '/pppk/': typeof PppkIndexRoute
  '/pyb/': typeof PybIndexRoute
  '/swasta/': typeof SwastaIndexRoute
  '/syarat-berkas/': typeof SyaratBerkasIndexRoute
  '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri': typeof PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRoute
  '/pns-negeri/cltn-negeri/cltn-negri': typeof PnsNegeriCltnNegeriCltnNegriRoute
  '/pns-negeri/melahirkan-negeri/melahirkan-negri': typeof PnsNegeriMelahirkanNegeriMelahirkanNegriRoute
  '/pns-negeri/negeri-besar/besar-negeri': typeof PnsNegeriNegeriBesarBesarNegeriRoute
  '/pns-negeri/sakit-negeri/sakit-negeri': typeof PnsNegeriSakitNegeriSakitNegeriRoute
  '/pns-negeri/tahunan-negeri/': typeof PnsNegeriTahunanNegeriIndexRoute
  '/pppk/cuti-melahirkan/': typeof PppkCutiMelahirkanIndexRoute
  '/pppk/cuti-sakit/': typeof PppkCutiSakitIndexRoute
  '/pppk/cuti-tahunan/': typeof PppkCutiTahunanIndexRoute
  '/swasta/cltn/': typeof SwastaCltnIndexRoute
  '/swasta/cuti-alasan-penting/': typeof SwastaCutiAlasanPentingIndexRoute
  '/swasta/cuti-melahirkan/': typeof SwastaCutiMelahirkanIndexRoute
  '/swasta/cuti-sakit/': typeof SwastaCutiSakitIndexRoute
  '/swasta/cuti-tahunan/': typeof SwastaCutiTahunanIndexRoute
  '/swasta/cutiBesar/': typeof SwastaCutiBesarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/e-presensi'
    | '/ketentuan'
    | '/prosedur'
    | '/riwayat-cuti'
    | '/ttd-cuti'
    | '/ttd-cuti-swasta'
    | '/pns-negeri/jenis-cuti'
    | '/pppk/jenis'
    | '/dasar-hukum'
    | '/pengajuan-cuti'
    | '/pns-negeri'
    | '/pppk'
    | '/pyb'
    | '/swasta'
    | '/syarat-berkas'
    | '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri'
    | '/pns-negeri/cltn-negeri/cltn-negri'
    | '/pns-negeri/melahirkan-negeri/melahirkan-negri'
    | '/pns-negeri/negeri-besar/besar-negeri'
    | '/pns-negeri/sakit-negeri/sakit-negeri'
    | '/pns-negeri/tahunan-negeri'
    | '/pppk/cuti-melahirkan'
    | '/pppk/cuti-sakit'
    | '/pppk/cuti-tahunan'
    | '/swasta/cltn'
    | '/swasta/cuti-alasan-penting'
    | '/swasta/cuti-melahirkan'
    | '/swasta/cuti-sakit'
    | '/swasta/cuti-tahunan'
    | '/swasta/cutiBesar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e-presensi'
    | '/ketentuan'
    | '/prosedur'
    | '/riwayat-cuti'
    | '/ttd-cuti'
    | '/ttd-cuti-swasta'
    | '/pns-negeri/jenis-cuti'
    | '/pppk/jenis'
    | '/dasar-hukum'
    | '/pengajuan-cuti'
    | '/pns-negeri'
    | '/pppk'
    | '/pyb'
    | '/swasta'
    | '/syarat-berkas'
    | '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri'
    | '/pns-negeri/cltn-negeri/cltn-negri'
    | '/pns-negeri/melahirkan-negeri/melahirkan-negri'
    | '/pns-negeri/negeri-besar/besar-negeri'
    | '/pns-negeri/sakit-negeri/sakit-negeri'
    | '/pns-negeri/tahunan-negeri'
    | '/pppk/cuti-melahirkan'
    | '/pppk/cuti-sakit'
    | '/pppk/cuti-tahunan'
    | '/swasta/cltn'
    | '/swasta/cuti-alasan-penting'
    | '/swasta/cuti-melahirkan'
    | '/swasta/cuti-sakit'
    | '/swasta/cuti-tahunan'
    | '/swasta/cutiBesar'
  id:
    | '__root__'
    | '/'
    | '/e-presensi'
    | '/ketentuan'
    | '/prosedur'
    | '/riwayat-cuti'
    | '/ttd-cuti'
    | '/ttd-cuti-swasta'
    | '/pns-negeri/jenis-cuti'
    | '/pppk/jenis'
    | '/dasar-hukum/'
    | '/pengajuan-cuti/'
    | '/pns-negeri/'
    | '/pppk/'
    | '/pyb/'
    | '/swasta/'
    | '/syarat-berkas/'
    | '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri'
    | '/pns-negeri/cltn-negeri/cltn-negri'
    | '/pns-negeri/melahirkan-negeri/melahirkan-negri'
    | '/pns-negeri/negeri-besar/besar-negeri'
    | '/pns-negeri/sakit-negeri/sakit-negeri'
    | '/pns-negeri/tahunan-negeri/'
    | '/pppk/cuti-melahirkan/'
    | '/pppk/cuti-sakit/'
    | '/pppk/cuti-tahunan/'
    | '/swasta/cltn/'
    | '/swasta/cuti-alasan-penting/'
    | '/swasta/cuti-melahirkan/'
    | '/swasta/cuti-sakit/'
    | '/swasta/cuti-tahunan/'
    | '/swasta/cutiBesar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EPresensiRoute: typeof EPresensiRoute
  KetentuanRoute: typeof KetentuanRoute
  ProsedurRoute: typeof ProsedurRoute
  RiwayatCutiRoute: typeof RiwayatCutiRoute
  TtdCutiRoute: typeof TtdCutiRoute
  TtdCutiSwastaRoute: typeof TtdCutiSwastaRoute
  PnsNegeriJenisCutiRoute: typeof PnsNegeriJenisCutiRoute
  PppkJenisRoute: typeof PppkJenisRoute
  DasarHukumIndexRoute: typeof DasarHukumIndexRoute
  PengajuanCutiIndexRoute: typeof PengajuanCutiIndexRoute
  PnsNegeriIndexRoute: typeof PnsNegeriIndexRoute
  PppkIndexRoute: typeof PppkIndexRoute
  PybIndexRoute: typeof PybIndexRoute
  SwastaIndexRoute: typeof SwastaIndexRoute
  SyaratBerkasIndexRoute: typeof SyaratBerkasIndexRoute
  PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRoute: typeof PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRoute
  PnsNegeriCltnNegeriCltnNegriRoute: typeof PnsNegeriCltnNegeriCltnNegriRoute
  PnsNegeriMelahirkanNegeriMelahirkanNegriRoute: typeof PnsNegeriMelahirkanNegeriMelahirkanNegriRoute
  PnsNegeriNegeriBesarBesarNegeriRoute: typeof PnsNegeriNegeriBesarBesarNegeriRoute
  PnsNegeriSakitNegeriSakitNegeriRoute: typeof PnsNegeriSakitNegeriSakitNegeriRoute
  PnsNegeriTahunanNegeriIndexRoute: typeof PnsNegeriTahunanNegeriIndexRoute
  PppkCutiMelahirkanIndexRoute: typeof PppkCutiMelahirkanIndexRoute
  PppkCutiSakitIndexRoute: typeof PppkCutiSakitIndexRoute
  PppkCutiTahunanIndexRoute: typeof PppkCutiTahunanIndexRoute
  SwastaCltnIndexRoute: typeof SwastaCltnIndexRoute
  SwastaCutiAlasanPentingIndexRoute: typeof SwastaCutiAlasanPentingIndexRoute
  SwastaCutiMelahirkanIndexRoute: typeof SwastaCutiMelahirkanIndexRoute
  SwastaCutiSakitIndexRoute: typeof SwastaCutiSakitIndexRoute
  SwastaCutiTahunanIndexRoute: typeof SwastaCutiTahunanIndexRoute
  SwastaCutiBesarIndexRoute: typeof SwastaCutiBesarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ttd-cuti-swasta': {
      id: '/ttd-cuti-swasta'
      path: '/ttd-cuti-swasta'
      fullPath: '/ttd-cuti-swasta'
      preLoaderRoute: typeof TtdCutiSwastaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ttd-cuti': {
      id: '/ttd-cuti'
      path: '/ttd-cuti'
      fullPath: '/ttd-cuti'
      preLoaderRoute: typeof TtdCutiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat-cuti': {
      id: '/riwayat-cuti'
      path: '/riwayat-cuti'
      fullPath: '/riwayat-cuti'
      preLoaderRoute: typeof RiwayatCutiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosedur': {
      id: '/prosedur'
      path: '/prosedur'
      fullPath: '/prosedur'
      preLoaderRoute: typeof ProsedurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ketentuan': {
      id: '/ketentuan'
      path: '/ketentuan'
      fullPath: '/ketentuan'
      preLoaderRoute: typeof KetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-presensi': {
      id: '/e-presensi'
      path: '/e-presensi'
      fullPath: '/e-presensi'
      preLoaderRoute: typeof EPresensiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-berkas/': {
      id: '/syarat-berkas/'
      path: '/syarat-berkas'
      fullPath: '/syarat-berkas'
      preLoaderRoute: typeof SyaratBerkasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swasta/': {
      id: '/swasta/'
      path: '/swasta'
      fullPath: '/swasta'
      preLoaderRoute: typeof SwastaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyb/': {
      id: '/pyb/'
      path: '/pyb'
      fullPath: '/pyb'
      preLoaderRoute: typeof PybIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pppk/': {
      id: '/pppk/'
      path: '/pppk'
      fullPath: '/pppk'
      preLoaderRoute: typeof PppkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pns-negeri/': {
      id: '/pns-negeri/'
      path: '/pns-negeri'
      fullPath: '/pns-negeri'
      preLoaderRoute: typeof PnsNegeriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengajuan-cuti/': {
      id: '/pengajuan-cuti/'
      path: '/pengajuan-cuti'
      fullPath: '/pengajuan-cuti'
      preLoaderRoute: typeof PengajuanCutiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dasar-hukum/': {
      id: '/dasar-hukum/'
      path: '/dasar-hukum'
      fullPath: '/dasar-hukum'
      preLoaderRoute: typeof DasarHukumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pppk/jenis': {
      id: '/pppk/jenis'
      path: '/pppk/jenis'
      fullPath: '/pppk/jenis'
      preLoaderRoute: typeof PppkJenisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pns-negeri/jenis-cuti': {
      id: '/pns-negeri/jenis-cuti'
      path: '/pns-negeri/jenis-cuti'
      fullPath: '/pns-negeri/jenis-cuti'
      preLoaderRoute: typeof PnsNegeriJenisCutiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swasta/cutiBesar/': {
      id: '/swasta/cutiBesar/'
      path: '/swasta/cutiBesar'
      fullPath: '/swasta/cutiBesar'
      preLoaderRoute: typeof SwastaCutiBesarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swasta/cuti-tahunan/': {
      id: '/swasta/cuti-tahunan/'
      path: '/swasta/cuti-tahunan'
      fullPath: '/swasta/cuti-tahunan'
      preLoaderRoute: typeof SwastaCutiTahunanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swasta/cuti-sakit/': {
      id: '/swasta/cuti-sakit/'
      path: '/swasta/cuti-sakit'
      fullPath: '/swasta/cuti-sakit'
      preLoaderRoute: typeof SwastaCutiSakitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swasta/cuti-melahirkan/': {
      id: '/swasta/cuti-melahirkan/'
      path: '/swasta/cuti-melahirkan'
      fullPath: '/swasta/cuti-melahirkan'
      preLoaderRoute: typeof SwastaCutiMelahirkanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swasta/cuti-alasan-penting/': {
      id: '/swasta/cuti-alasan-penting/'
      path: '/swasta/cuti-alasan-penting'
      fullPath: '/swasta/cuti-alasan-penting'
      preLoaderRoute: typeof SwastaCutiAlasanPentingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swasta/cltn/': {
      id: '/swasta/cltn/'
      path: '/swasta/cltn'
      fullPath: '/swasta/cltn'
      preLoaderRoute: typeof SwastaCltnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pppk/cuti-tahunan/': {
      id: '/pppk/cuti-tahunan/'
      path: '/pppk/cuti-tahunan'
      fullPath: '/pppk/cuti-tahunan'
      preLoaderRoute: typeof PppkCutiTahunanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pppk/cuti-sakit/': {
      id: '/pppk/cuti-sakit/'
      path: '/pppk/cuti-sakit'
      fullPath: '/pppk/cuti-sakit'
      preLoaderRoute: typeof PppkCutiSakitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pppk/cuti-melahirkan/': {
      id: '/pppk/cuti-melahirkan/'
      path: '/pppk/cuti-melahirkan'
      fullPath: '/pppk/cuti-melahirkan'
      preLoaderRoute: typeof PppkCutiMelahirkanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pns-negeri/tahunan-negeri/': {
      id: '/pns-negeri/tahunan-negeri/'
      path: '/pns-negeri/tahunan-negeri'
      fullPath: '/pns-negeri/tahunan-negeri'
      preLoaderRoute: typeof PnsNegeriTahunanNegeriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pns-negeri/sakit-negeri/sakit-negeri': {
      id: '/pns-negeri/sakit-negeri/sakit-negeri'
      path: '/pns-negeri/sakit-negeri/sakit-negeri'
      fullPath: '/pns-negeri/sakit-negeri/sakit-negeri'
      preLoaderRoute: typeof PnsNegeriSakitNegeriSakitNegeriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pns-negeri/negeri-besar/besar-negeri': {
      id: '/pns-negeri/negeri-besar/besar-negeri'
      path: '/pns-negeri/negeri-besar/besar-negeri'
      fullPath: '/pns-negeri/negeri-besar/besar-negeri'
      preLoaderRoute: typeof PnsNegeriNegeriBesarBesarNegeriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pns-negeri/melahirkan-negeri/melahirkan-negri': {
      id: '/pns-negeri/melahirkan-negeri/melahirkan-negri'
      path: '/pns-negeri/melahirkan-negeri/melahirkan-negri'
      fullPath: '/pns-negeri/melahirkan-negeri/melahirkan-negri'
      preLoaderRoute: typeof PnsNegeriMelahirkanNegeriMelahirkanNegriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pns-negeri/cltn-negeri/cltn-negri': {
      id: '/pns-negeri/cltn-negeri/cltn-negri'
      path: '/pns-negeri/cltn-negeri/cltn-negri'
      fullPath: '/pns-negeri/cltn-negeri/cltn-negri'
      preLoaderRoute: typeof PnsNegeriCltnNegeriCltnNegriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri': {
      id: '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri'
      path: '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri'
      fullPath: '/pns-negeri/alasanPenting-negeri/alasanPenting-negeri'
      preLoaderRoute: typeof PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EPresensiRoute: EPresensiRoute,
  KetentuanRoute: KetentuanRoute,
  ProsedurRoute: ProsedurRoute,
  RiwayatCutiRoute: RiwayatCutiRoute,
  TtdCutiRoute: TtdCutiRoute,
  TtdCutiSwastaRoute: TtdCutiSwastaRoute,
  PnsNegeriJenisCutiRoute: PnsNegeriJenisCutiRoute,
  PppkJenisRoute: PppkJenisRoute,
  DasarHukumIndexRoute: DasarHukumIndexRoute,
  PengajuanCutiIndexRoute: PengajuanCutiIndexRoute,
  PnsNegeriIndexRoute: PnsNegeriIndexRoute,
  PppkIndexRoute: PppkIndexRoute,
  PybIndexRoute: PybIndexRoute,
  SwastaIndexRoute: SwastaIndexRoute,
  SyaratBerkasIndexRoute: SyaratBerkasIndexRoute,
  PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRoute:
    PnsNegeriAlasanPentingNegeriAlasanPentingNegeriRoute,
  PnsNegeriCltnNegeriCltnNegriRoute: PnsNegeriCltnNegeriCltnNegriRoute,
  PnsNegeriMelahirkanNegeriMelahirkanNegriRoute:
    PnsNegeriMelahirkanNegeriMelahirkanNegriRoute,
  PnsNegeriNegeriBesarBesarNegeriRoute: PnsNegeriNegeriBesarBesarNegeriRoute,
  PnsNegeriSakitNegeriSakitNegeriRoute: PnsNegeriSakitNegeriSakitNegeriRoute,
  PnsNegeriTahunanNegeriIndexRoute: PnsNegeriTahunanNegeriIndexRoute,
  PppkCutiMelahirkanIndexRoute: PppkCutiMelahirkanIndexRoute,
  PppkCutiSakitIndexRoute: PppkCutiSakitIndexRoute,
  PppkCutiTahunanIndexRoute: PppkCutiTahunanIndexRoute,
  SwastaCltnIndexRoute: SwastaCltnIndexRoute,
  SwastaCutiAlasanPentingIndexRoute: SwastaCutiAlasanPentingIndexRoute,
  SwastaCutiMelahirkanIndexRoute: SwastaCutiMelahirkanIndexRoute,
  SwastaCutiSakitIndexRoute: SwastaCutiSakitIndexRoute,
  SwastaCutiTahunanIndexRoute: SwastaCutiTahunanIndexRoute,
  SwastaCutiBesarIndexRoute: SwastaCutiBesarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
